### ISSUE TITLE
Demo Gif

### ISSUE THREAD

**Issue by JarrodCTaylor** [JarrodCTaylor/vim-sql-suggest#1]
![sql-suggest](https://cloud.githubusercontent.com/assets/4416952/4486307/1e79a0d6-49df-11e4-9f42-8b9149d28297.gif)

**Comment by Disco-Dave** [comment]
What setting or plugin do you have that is automatically upper casing the keywords for you?

**Comment by JarrodCTaylor** [comment]
`ftplugin/sql.vim`

``` 
:iabbr <buffer> select SELECT
:iabbr <buffer> from FROM
...
````
